imports:
    - { resource: parameters.ini }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        storage_id:     pdo
        db_table:       sessions
        db_id_col:      id
        db_data_col:    data
        db_time_col:    last_updated
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        logging:  %kernel.debug%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
            AcmeExpensesBundle: ~

security:
    providers:
        # fos_userbundle:
            # id: fos_user.user_manager
        main:
            users:
                foo: { password: testing, roles: ROLE_USER }
                admin: { password: admin, roles: ROLE_ADMIN }
    factories:
        FunsationalCASFactory: %kernel.root_dir%/../src/Funsational/CASBundle/Resources/config/security_factories.xml
    firewalls:
        profiler:
            pattern: /_profiler/.*
        wdt:
            pattern: /_wdt/.*
        main:
            pattern: /.*
            cas:
                default_domain: sync.expensetracker.com
            form_login:
                use_forward: false
                provider: main
                use_forward: false
            logout: true

# Swiftmailer Configuration
#swiftmailer:
#    transport:  %mailer_transport%
#    host:       %mailer_host%
#    username:   %mailer_user%
#    password:   %mailer_password%
