_welcome:
    resource: "@AcmeExpensesBundle/Controller/WelcomeController.php"
    type:     annotation

_demo_secured:
    resource: "@AcmeExpensesBundle/Controller/ExpensesController.php"
    type:     annotation

_demo:
    resource: "@AcmeExpensesBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
